# Starter pipeline

trigger:
- main

pool:
   vmImage: 'ubuntu-16.04' # set to windows-latest or another Windows vmImage for Windows builds

steps:

- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'Image scan console'
    artifact: 'nginx:latest'
    project: 'Azure Devops Compute Scan'